export default {
	'zotero.appName': 'Zotero',
	'general.etAl': '외',
	'general.back': '뒤로',
	'general.thanksForHelpingImprove': '%S 개선에 도움을 주셔서 감사합니다!',
	'general.tryAgain': '다시 시도',
	'general.updateAvailable': '업데이트 사용 가능',
	'general.copyToClipboard': '클립보드에 복사',
	'general.finished': '완료',
	'general.checkForUpdates': '업데이트 확인',
	'general.keys.cmdShift': 'Cmd+Shift+',
	'general.clear': '지우기',
	'general.failed': '실패',
	'general.restartLater': '나중에 재시작',
	'general.unknownErrorOccurred': '알 수 없는 오류가 발생했습니다.',
	'general.dontShowAgainFor': '오늘 다시 표시하지 않음;%1$S일 동안 다시 표시하지 않음',
	'general.permissionDenied': '권한 거부됨',
	'general.checkForUpdate': '업데이트 확인',
	'general.moreInformation': '자세한 정보',
	'general.quitApp': '%S 종료',
	'general.errorHasOccurred': '오류가 발생했습니다.',
	'general.and': '그리고',
	'general.isUpToDate': '%S가 최신 상태입니다.',
	'general.seeForMoreInformation': '자세한 정보는 %S를 참조하세요.',
	'general.success': '성공',
	'general.submitted': '제출됨',
	'general.character.plural': '글자',
	'general.locate': '찾기…',
	'general.restartNow': '지금 재시작',
	'general.pleaseRestart': '%S를 재시작해 주세요.',
	'general.quit': '종료',
	'general.hide': '숨기기',
	'general.browserIsOffline': '%S가 현재 오프라인 모드입니다.',
	'general.error': '오류',
	'general.import': '가져오기',
	'general.warning': '경고',
	'general.yes': '예',
	'general.useDefault': '기본값 사용',
	'general.fix': '수정…',
	'general.restartRequiredForChanges': '변경 사항을 적용하려면 %S를 재시작해야 합니다.',
	'general.accessDenied': '접근 거부됨',
	'general.continue': '계속',
	'general.dontShowAgain': '다시 표시하지 않음',
	'general.copy': '복사',
	'general.keys.ctrlShift': 'Ctrl+Shift+',
	'general.close': '닫기',
	'general.create': '만들기',
	'general.export': '내보내기',
	'general.noUpdatesFound': '업데이트를 찾을 수 없음',
	'general.restartRequired': '재시작 필요',
	'general.actionCannotBeUndone': '이 작업은 실행 취소할 수 없습니다.',
	'general.pdf': 'PDF',
	'general.remove': '제거',
	'general.cancel': '취소',
	'general.tryLater': '나중에 시도',
	'general.operationInProgress.waitUntilFinishedAndTryAgain': '완료될 때까지 기다린 후 다시 시도해 주세요.',
	'general.processing': '처리 중',
	'general.disable': '비활성화',
	'general.restartApp': '%S 재시작',
	'general.enable': '활성화',
	'general.showDirectory': '디렉토리 표시',
	'general.passed': '통과',
	'general.invalidResponseServer': '서버에서 잘못된 응답을 받았습니다.',
	'general.reset': '재설정',
	'general.nMegabytes': '%S MB',
	'general.numMore': '%S개 더…',
	'general.serverError': '서버에서 오류가 발생했습니다. 다시 시도해 주세요.',
	'general.upgrade': '업그레이드',
	'general.open': '%S 열기',
	'general.openPreferences': '환경설정 열기',
	'general.describeProblem': '문제를 간단히 설명해 주세요:',
	'general.pleaseRestartAndTryAgain': '%S를 재시작한 후 다시 시도해 주세요.',
	'general.operationInProgress.waitUntilFinished': '완료될 때까지 기다려 주세요.',
	'general.dontShowWarningAgain': '이 경고를 다시 표시하지 않기',
	'general.notNow': '나중에',
	'general.item': '항목',
	'general.restartRequiredForChange': '변경 사항을 적용하려면 %S를 재시작해야 합니다.',
	'general.character.singular': '글자',
	'general.operationInProgress': 'Zotero 작업이 현재 진행 중입니다.',
	'general.no': '아니오',
	'general.delete': '삭제',
	'general.openDocumentation': '문서 열기',
	'general.tryAgainLater': '몇 분 후에 다시 시도해 주세요.',
	'general.install': '설치',
	'general.yellow': '노란색',
	'general.red': '빨간색',
	'general.green': '초록색',
	'general.blue': '파란색',
	'general.purple': '보라색',
	'general.magenta': '마젠타',
	'general.orange': '주황색',
	'general.gray': '회색',
	'general.black': '검은색',
	'general.showInLibrary': '라이브러리에서 표시',
	'general.clearSelection': '선택 해제',
	'general.update': '업데이트',
	'general.print': '인쇄',
	'general.save': '저장',
	'general.edit': '편집',
	'pdfReader.annotations': '주석',
	'pdfReader.showAnnotations': '주석 표시',
	'pdfReader.searchAnnotations': '주석 검색',
	'pdfReader.searchOutline': '목차 검색',
	'pdfReader.noAnnotations': '사이드바에서 보려면 주석을 만드세요',
	'pdfReader.noExtractedText': '추출된 텍스트 없음',
	'pdfReader.addComment': '댓글 추가',
	'pdfReader.annotationComment': '주석 댓글',
	'pdfReader.annotationText': '주석 텍스트',
	'pdfReader.manageTags': '이 주석의 태그 관리',
	'pdfReader.openMenu': '주석 메뉴 열기',
	'pdfReader.thumbnails': '썸네일',
	'pdfReader.tagSelectorMessage': '이 태그로 주석 필터링',
	'pdfReader.addTags': '태그 추가…',
	'pdfReader.highlightText': '텍스트 하이라이트',
	'pdfReader.underlineText': '텍스트 밑줄',
	'pdfReader.addNote': '노트 추가',
	'pdfReader.selectArea': '영역 선택',
	'pdfReader.addText': '텍스트 추가',
	'pdfReader.draw': '그리기',
	'pdfReader.highlightAnnotation': '하이라이트 주석',
	'pdfReader.underlineAnnotation': '밑줄 주석',
	'pdfReader.noteAnnotation': '노트 주석',
	'pdfReader.textAnnotation': '텍스트 주석',
	'pdfReader.imageAnnotation': '이미지 주석',
	'pdfReader.inkAnnotation': '잉크 주석',
	'pdfReader.searchResultIndex': '검색 결과',
	'pdfReader.searchResultTotal': '전체 검색 결과',
	'pdfReader.eraser': '지우개',
	'pdfReader.pickColor': '색상 선택',
	'pdfReader.addToNote': '노트에 추가',
	'pdfReader.zoomIn': '확대',
	'pdfReader.zoomOut': '축소',
	'pdfReader.zoomReset': '확대/축소 재설정',
	'pdfReader.zoomAuto': '자동 크기 조정',
	'pdfReader.zoomPageWidth': '페이지 너비로 확대',
	'pdfReader.zoomPageHeight': '페이지 높이로 확대',
	'pdfReader.splitVertically': '세로 분할',
	'pdfReader.splitHorizontally': '가로 분할',
	'pdfReader.nextPage': '다음 페이지',
	'pdfReader.previousPage': '이전 페이지',
	'pdfReader.page': '페이지',
	'pdfReader.location': '위치',
	'pdfReader.readOnly': '읽기 전용',
	'pdfReader.promptTransferFromPDF.title': '주석 가져오기',
	'pdfReader.promptTransferFromPDF.text': 'PDF 파일에 저장된 주석이 %1$S로 이동됩니다.',
	'pdfReader.promptTransferToPDF.title': '파일에 주석 저장',
	'pdfReader.promptTransferToPDF.text': '주석이 PDF 파일로 전송되며 %S에서 더 이상 편집할 수 없습니다.',
	'pdfReader.promptPasswordProtected': '비밀번호로 보호된 PDF 파일에서는 이 작업을 지원하지 않습니다.',
	'pdfReader.rotateLeft': '왼쪽으로 회전',
	'pdfReader.rotateRight': '오른쪽으로 회전',
	'pdfReader.editPageNumber': '페이지 번호 편집…',
	'pdfReader.editAnnotationText': '주석 텍스트 편집',
	'pdfReader.copyImage': '이미지 복사',
	'pdfReader.saveImageAs': '이미지를 다른 이름으로 저장…',
	'pdfReader.pageNumberPopupHeader': '페이지 번호 변경 대상:',
	'pdfReader.thisAnnotation': '이 주석',
	'pdfReader.selectedAnnotations': '선택된 주석',
	'pdfReader.thisPage': '이 페이지',
	'pdfReader.thisPageAndLaterPages': '이 페이지와 이후 페이지',
	'pdfReader.allPages': '모든 페이지',
	'pdfReader.autoDetect': '자동 감지',
	'pdfReader.appearance': '모양',
	'pdfReader.epubAppearance.lineHeight': '줄 간격',
	'pdfReader.epubAppearance.wordSpacing': '단어 간격',
	'pdfReader.epubAppearance.letterSpacing': '글자 간격',
	'pdfReader.epubAppearance.pageWidth': '페이지 너비',
	'pdfReader.epubAppearance.useOriginalFont': '원본 글꼴 사용',
	'pdfReader.epubAppearance.lineHeight.revert': '기본 줄 간격 사용',
	'pdfReader.epubAppearance.wordSpacing.revert': '기본 단어 간격 사용',
	'pdfReader.epubAppearance.letterSpacing.revert': '기본 글자 간격 사용',
	'pdfReader.epubAppearance.pageWidth.revert': '기본 페이지 너비 사용',
	'pdfReader.deleteAnnotation.singular': '선택한 주석을 삭제하시겠습니까?',
	'pdfReader.deleteAnnotation.plural': '선택한 주석들을 삭제하시겠습니까?',
	'pdfReader.enterPassword': 'PDF 파일을 열기 위한 비밀번호를 입력하세요.',
	'pdfReader.includeAnnotations': '주석 포함',
	'pdfReader.preparingDocumentForPrinting': '인쇄를 위해 문서를 준비하는 중…',
	'pdfReader.phraseNotFound': '구문을 찾을 수 없음',
	'pdfReader.selectedPages': '{count, plural, one {페이지 #개} other {페이지 #개}} 선택됨',
	'pdfReader.pageOptions': '페이지 옵션',
	'pdfReader.epubEncrypted': '이 전자책은 암호화된 것 같으며 열 수 없습니다.',
	'pdfReader.find': '찾기',
	'pdfReader.close': '닫기',
	'pdfReader.showThumbnails': '썸네일 표시',
	'pdfReader.showOutline': '목차 표시',
	'pdfReader.findPrevious': '이전 구문 찾기',
	'pdfReader.findNext': '다음 구문 찾기',
	'pdfReader.toggleSidebar': '사이드바 토글',
	'pdfReader.findInDocument': '문서에서 찾기',
	'pdfReader.toggleContextPane': '컨텍스트 패널 토글',
	'pdfReader.highlightAll': '모두 하이라이트',
	'pdfReader.matchCase': '대소문자 구분',
	'pdfReader.wholeWords': '전체 단어',
	'pdfReader.convertToHighlight': '하이라이트로 변환',
	'pdfReader.convertToUnderline': '밑줄로 변환',
	'pdfReader.size': '크기',
	'pdfReader.merge': '병합',
	'pdfReader.copyLink': '링크 복사',
	'pdfReader.theme.original': '원본',
	'pdfReader.theme.snow': '눈',
	'pdfReader.theme.sepia': '세피아',
	'pdfReader.theme.dark': '다크',
	'pdfReader.addTheme': '테마 추가',
	'pdfReader.scrollMode': '스크롤',
	'pdfReader.spreadMode': '펼침',
	'pdfReader.flowMode': '페이지 레이아웃',
	'pdfReader.columns': '열',
	'pdfReader.splitView': '분할 보기',
	'pdfReader.themes': '테마',
	'pdfReader.vertical': '세로',
	'pdfReader.horizontal': '가로',
	'pdfReader.wrapped': '줄바꿈',
	'pdfReader.none': '없음',
	'pdfReader.odd': '홀수',
	'pdfReader.even': '짝수',
	'pdfReader.paginated': '페이지네이션',
	'pdfReader.scrolled': '스크롤됨',
	'pdfReader.single': '단일',
	'pdfReader.double': '이중',
	'pdfReader.themeName': '테마 이름:',
	'pdfReader.themeOptions': '테마 옵션',
	'pdfReader.background': '배경:',
	'pdfReader.foreground': '전경:',
}; 